# Generated by Django 4.1.7 on 2023-05-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_alter_enrollment_price_alter_membershipplan_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='birthday_day',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bot',
            name='birthday_month',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bot',
            name='birthday_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bot',
            name='birthday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bot',
            name='physical_Condition',
            field=models.CharField(blank=True, choices=[('ectomorph', 'Ectomorph'), ('mesomorph', 'Mesomorph'), ('endomorph', 'Endomorph')], max_length=20),
        ),
    ]
