# Generated by Django 4.1.7 on 2023-05-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_bot_birthday_day_bot_birthday_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='bot',
            name='birthday_day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bot',
            name='birthday_month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bot',
            name='birthday_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bot',
            name='physical_Condition',
            field=models.CharField(choices=[('ectomorph', 'Ectomorph'), ('mesomorph', 'Mesomorph'), ('endomorph', 'Endomorph')], max_length=20),
        ),
    ]
